Synchronizer mvc integration
Vicx95/file_synchronizer pull request #11
Opened 2023-01-05 13:41 UTC by MikeX-s

Changed clang-formatter to Microsoft style

2023-01-05 20:00 UTC, aniolm requested changes

2023-01-06 17:50 UTC, Vicx95 commented on src/model.cpp
> +
Myślę czy raw pointerów nie zamienić od razu w smart pointery, chyba że jest to planowane w późniejszym etapie

2023-01-06 17:52 UTC, Vicx95 commented on src/Scanner.cpp
> -std::pair<std::vector<PathAndTime>, std::vector<PathAndTime>> Scanner::comparingPreviousAndLastScanning(std::vector<PathAndTime> previous, std::vector<PathAndTime> last){
Moim zdaniem lepiej byłoby użyć alias, bardziej czytelne by było

2023-01-06 18:05 UTC, Vicx95 requested changes

2023-01-08 18:59 UTC, MikeX-s commented on src/model.cpp
> +
Proponuję zrobić to później, jak starczy czasu :)

2023-01-08 18:59 UTC, MikeX-s commented on src/controller.cpp
> +    // m_model->forceSync();
Do zrobienia

2023-01-08 19:04 UTC, merged